services:
  imageporter:
    build:
      context: .
      dockerfile: Dockerfile
    image: imageporter/imageporter:latest
    container_name: imageporter
    restart: no
    volumes:
      - ./images.json:/app/images.json:ro
      - ./accounts.json:/app/accounts.json:ro
    environment:
      TZ: "Asia/Shanghai"
      CRON: "* * * * *"
      RUN_ONCE: "false"
      DRY_RUN: "false"
      SLEEP_TIME: "5"
      RETRY_DELAY_TIME: "5"
