services:
  imageporter:
    build:
      context: .
      dockerfile: Dockerfile
    image: imageporter/imageporter:dev
    container_name: imageporter
    restart: no
    volumes:
      - ./images.json:/app/images.json:ro
    env_file:
      - .env
