name: Publish ImagePorter Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v2026.1.12.1'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: imageporter
        password: ${{ secrets.DockerHub_TOKEN }}

    - name: Set up Golang
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Go build executables
      run: |
        CGO_ENABLED=0 go install github.com/google/go-containerregistry/cmd/crane@latest && \
        CGO_ENABLED=0 go install github.com/aptible/supercronic@latest

    - name: Copy executables to workspace
      run: |
        cp $HOME/go/bin/crane $GITHUB_WORKSPACE/crane && \
        cp $HOME/go/bin/supercronic $GITHUB_WORKSPACE/supercronic

    - name: Check executables
      run: |
        ls -lh $GITHUB_WORKSPACE && \
        file $GITHUB_WORKSPACE/crane && \
        file $GITHUB_WORKSPACE/supercronic

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          imageporter/imageporter:latest
          imageporter/imageporter:${{ inputs.tag }}

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.tag }}
